import '../models/case.dart';
import '../models/client.dart';
import '../models/appointment.dart';
import '../models/task.dart';
import '../models/document.dart';
import '../models/notification.dart';
import '../models/payment.dart';

class DummyData {
  // Cases
  static List<Case> get cases => [
    Case(
      id: '1',
      title: 'Smith vs. Johnson',
      caseNumber: 'CV-2023-1234',
      clientId: '1',
      clientName: 'Robert Smith',
      court: 'Superior Court of California',
      status: 'Active',
      filingDate: DateTime(2023, 3, 15),
      nextHearing: DateTime.now().add(const Duration(days: 10)),
      description: 'Personal injury case involving a car accident on Highway 101. The client is seeking damages for medical expenses, lost wages, and pain and suffering.',
      caseType: 'Personal Injury',
      tags: ['Car Accident', 'Injury', 'Insurance'],
      documentIds: ['1', '2', '3'],
      relatedCaseIds: [],
    ),
    Case(
      id: '2',
      title: 'Williams Estate',
      caseNumber: 'PR-2023-5678',
      clientId: '2',
      clientName: 'Sarah Williams',
      court: 'Probate Court',
      status: 'Pending',
      filingDate: DateTime(2023, 2, 20),
      nextHearing: DateTime.now().add(const Duration(days: 15)),
      description: 'Estate administration for the late Mr. Williams. The case involves distributing assets to beneficiaries and resolving tax issues.',
      caseType: 'Probate',
      tags: ['Estate', 'Will', 'Inheritance'],
      documentIds: ['4', '5'],
      relatedCaseIds: [],
    ),
    Case(
      id: '3',
      title: 'Davis Divorce',
      caseNumber: 'FL-2023-9012',
      clientId: '3',
      clientName: 'Michael Davis',
      court: 'Family Court',
      status: 'Active',
      filingDate: DateTime(2023, 4, 5),
      nextHearing: DateTime.now().add(const Duration(days: 5)),
      description: 'Divorce proceedings including child custody and asset division. The client is seeking primary custody of two children and equitable distribution of marital assets.',
      caseType: 'Family Law',
      tags: ['Divorce', 'Custody', 'Assets'],
      documentIds: ['6', '7', '8'],
      relatedCaseIds: [],
    ),
    Case(
      id: '4',
      title: 'Thompson LLC Formation',
      caseNumber: 'BL-2023-3456',
      clientId: '4',
      clientName: 'Jennifer Thompson',
      court: 'N/A',
      status: 'Completed',
      filingDate: DateTime(2023, 1, 10),
      nextHearing: DateTime(2023, 1, 10),
      description: 'Formation of an LLC for a new tech startup. The client needed assistance with articles of organization, operating agreement, and initial corporate governance.',
      caseType: 'Business Law',
      tags: ['LLC', 'Startup', 'Business Formation'],
      documentIds: ['9', '10'],
      relatedCaseIds: [],
    ),
    Case(
      id: '5',
      title: 'Brown Property Dispute',
      caseNumber: 'CV-2023-7890',
      clientId: '5',
      clientName: 'James Brown',
      court: 'Civil Court',
      status: 'Active',
      filingDate: DateTime(2023, 3, 30),
      nextHearing: DateTime.now().add(const Duration(days: 20)),
      description: 'Boundary dispute with neighboring property owner. The dispute involves a contested property line and alleged encroachment by the neighbor\'s new fence.',
      caseType: 'Real Estate',
      tags: ['Property', 'Boundary', 'Dispute'],
      documentIds: ['11', '12'],
      relatedCaseIds: [],
    ),
    Case(
      id: '6',
      title: 'Garcia Patent Application',
      caseNumber: 'IP-2023-4567',
      clientId: '6',
      clientName: 'Carlos Garcia',
      court: 'USPTO',
      status: 'Pending',
      filingDate: DateTime(2023, 5, 12),
      nextHearing: DateTime.now().add(const Duration(days: 60)),
      description: 'Patent application for a new medical device. The client has developed an innovative diagnostic tool and needs to secure intellectual property protection.',
      caseType: 'Intellectual Property',
      tags: ['Patent', 'Medical', 'Innovation'],
      documentIds: ['13', '14'],
      relatedCaseIds: [],
    ),
    Case(
      id: '7',
      title: 'Wilson Contract Dispute',
      caseNumber: 'CV-2023-8901',
      clientId: '7',
      clientName: 'Thomas Wilson',
      court: 'Commercial Court',
      status: 'Active',
      filingDate: DateTime(2023, 4, 18),
      nextHearing: DateTime.now().add(const Duration(days: 12)),
      description: 'Breach of contract dispute with a supplier. The client alleges that the supplier failed to deliver goods according to the agreed specifications and timeline.',
      caseType: 'Contract Law',
      tags: ['Contract', 'Business', 'Breach'],
      documentIds: ['15', '16', '17'],
      relatedCaseIds: [],
    ),
    Case(
      id: '8',
      title: 'Martinez Immigration',
      caseNumber: 'IM-2023-2345',
      clientId: '8',
      clientName: 'Elena Martinez',
      court: 'Immigration Court',
      status: 'Pending',
      filingDate: DateTime(2023, 6, 5),
      nextHearing: DateTime.now().add(const Duration(days: 30)),
      description: 'Family-based immigration petition. The client is seeking permanent residency for her spouse who is currently living abroad.',
      caseType: 'Immigration',
      tags: ['Family', 'Residency', 'Petition'],
      documentIds: ['18', '19'],
      relatedCaseIds: [],
    ),
  ];

  // Clients
  static List<Client> get clients => [
    Client(
      id: '1',
      name: 'Robert Smith',
      email: 'robert.smith@example.com',
      phone: '(555) 123-4567',
      address: '123 Main St, San Francisco, CA 94105',
      imageUrl: 'https://randomuser.me/api/portraits/men/32.jpg',
      caseIds: ['1'],
      clientSince: DateTime(2022, 10, 15),
      notes: 'Prefers communication via email. Available after 5 PM on weekdays.',
    ),
    Client(
      id: '2',
      name: 'Sarah Williams',
      email: 'sarah.williams@example.com',
      phone: '(555) 234-5678',
      address: '456 Oak Ave, Los Angeles, CA 90001',
      imageUrl: 'https://randomuser.me/api/portraits/women/44.jpg',
      caseIds: ['2'],
      clientSince: DateTime(2021, 5, 20),
      notes: 'Executor of Williams Estate. Has two children who are beneficiaries.',
    ),
    Client(
      id: '3',
      name: 'Michael Davis',
      email: 'michael.davis@example.com',
      phone: '(555) 345-6789',
      address: '789 Pine St, San Diego, CA 92101',
      imageUrl: 'https://randomuser.me/api/portraits/men/45.jpg',
      caseIds: ['3'],
      clientSince: DateTime(2023, 1, 10),
      notes: 'Going through difficult divorce. Has 2 children, ages 8 and 10.',
    ),
    Client(
      id: '4',
      name: 'Jennifer Thompson',
      email: 'jennifer.thompson@example.com',
      phone: '(555) 456-7890',
      address: '101 Tech Blvd, San Jose, CA 95110',
      imageUrl: 'https://randomuser.me/api/portraits/women/22.jpg',
      caseIds: ['4'],
      clientSince: DateTime(2022, 12, 5),
      notes: 'Tech entrepreneur starting new venture. Needs ongoing legal support.',
    ),
    Client(
      id: '5',
      name: 'James Brown',
      email: 'james.brown@example.com',
      phone: '(555) 567-8901',
      address: '202 Cedar Rd, Sacramento, CA 95814',
      imageUrl: 'https://randomuser.me/api/portraits/men/67.jpg',
      caseIds: ['5'],
      clientSince: DateTime(2023, 2, 15),
      notes: 'Retired teacher. Property has been in family for generations.',
    ),
    Client(
      id: '6',
      name: 'Carlos Garcia',
      email: 'carlos.garcia@example.com',
      phone: '(555) 678-9012',
      address: '303 Maple Dr, Fresno, CA 93721',
      imageUrl: 'https://randomuser.me/api/portraits/men/55.jpg',
      caseIds: ['6'],
      clientSince: DateTime(2023, 3, 8),
      notes: 'Medical researcher with multiple patents. Very detail-oriented.',
    ),
    Client(
      id: '7',
      name: 'Thomas Wilson',
      email: 'thomas.wilson@example.com',
      phone: '(555) 789-0123',
      address: '404 Birch Ln, Oakland, CA 94612',
      imageUrl: 'https://randomuser.me/api/portraits/men/22.jpg',
      caseIds: ['7'],
      clientSince: DateTime(2022, 8, 12),
      notes: 'Small business owner. Has had previous contract issues with suppliers.',
    ),
    Client(
      id: '8',
      name: 'Elena Martinez',
      email: 'elena.martinez@example.com',
      phone: '(555) 890-1234',
      address: '505 Elm St, Santa Ana, CA 92701',
      imageUrl: 'https://randomuser.me/api/portraits/women/33.jpg',
      caseIds: ['8'],
      clientSince: DateTime(2023, 4, 22),
      notes: 'Works as a nurse. Trying to bring spouse to the US from Mexico.',
    ),
  ];

  // Appointments
  static List<Appointment> get appointments {
    final now = DateTime.now();
    final today = DateTime(now.year, now.month, now.day);
    
    return [
      Appointment(
        id: '1',
        title: 'Initial Consultation',
        startTime: today.add(const Duration(days: 1, hours: 10)),
        endTime: today.add(const Duration(days: 1, hours: 11)),
        clientName: 'Robert Smith',
        clientId: '1',
        location: 'Office',
        description: 'Discuss case details and legal options for the personal injury claim.',
        type: 'Consultation',
        isRemote: false,
        caseId: '1',
        caseTitle: 'Smith vs. Johnson',
      ),
      Appointment(
        id: '2',
        title: 'Document Review',
        startTime: today.add(const Duration(days: 2, hours: 14)),
        endTime: today.add(const Duration(days: 2, hours: 15, minutes: 30)),
        clientName: 'Sarah Williams',
        clientId: '2',
        location: 'Virtual Meeting',
        description: 'Review estate documents and will for the Williams Estate case.',
        type: 'Document Review',
        isRemote: true,
        caseId: '2',
        caseTitle: 'Williams Estate',
      ),
      Appointment(
        id: '3',
        title: 'Court Hearing',
        startTime: today.add(const Duration(days: 3, hours: 9)),
        endTime: today.add(const Duration(days: 3, hours: 11)),
        clientName: 'Michael Davis',
        clientId: '3',
        location: 'Family Court, Room 305',
        description: 'Initial hearing for divorce proceedings. Need to present arguments for temporary custody arrangement.',
        type: 'Court Appearance',
        isRemote: false,
        caseId: '3',
        caseTitle: 'Davis Divorce',
      ),
      Appointment(
        id: '4',
        title: 'Contract Signing',
        startTime: today.add(const Duration(days: 4, hours: 15)),
        endTime: today.add(const Duration(days: 4, hours: 16)),
        clientName: 'Jennifer Thompson',
        clientId: '4',
        location: 'Office',
        description: 'Sign LLC formation documents for the new tech startup.',
        type: 'Document Signing',
        isRemote: false,
        caseId: '4',
        caseTitle: 'Thompson LLC Formation',
      ),
      Appointment(
        id: '5',
        title: 'Mediation Session',
        startTime: today.add(const Duration(days: 5, hours: 13)),
        endTime: today.add(const Duration(days: 5, hours: 15)),
        clientName: 'James Brown',
        clientId: '5',
        location: 'Mediation Center',
        description: 'Mediation with neighboring property owner to resolve the boundary dispute.',
        type: 'Mediation',
        isRemote: false,
        caseId: '5',
        caseTitle: 'Brown Property Dispute',
      ),
      Appointment(
        id: '6',
        title: 'Patent Review',
        startTime: today.add(const Duration(days: 2, hours: 11)),
        endTime: today.add(const Duration(days: 2, hours: 12)),
        clientName: 'Carlos Garcia',
        clientId: '6',
        location: 'Virtual Meeting',
        description: 'Review patent application documents before submission to USPTO.',
        type: 'Document Review',
        isRemote: true,
        caseId: '6',
        caseTitle: 'Garcia Patent Application',
      ),
      Appointment(
        id: '7',
        title: 'Settlement Discussion',
        startTime: today.add(const Duration(days: 3, hours: 14)),
        endTime: today.add(const Duration(days: 3, hours: 15)),
        clientName: 'Thomas Wilson',
        clientId: '7',
        location: 'Office',
        description: 'Discuss potential settlement terms for the contract dispute case.',
        type: 'Consultation',
        isRemote: false,
        caseId: '7',
        caseTitle: 'Wilson Contract Dispute',
      ),
      Appointment(
        id: '8',
        title: 'Immigration Interview Prep',
        startTime: today.add(const Duration(days: 4, hours: 10)),
        endTime: today.add(const Duration(days: 4, hours: 11, minutes: 30)),
        clientName: 'Elena Martinez',
        clientId: '8',
        location: 'Virtual Meeting',
        description: 'Prepare client for upcoming USCIS interview for family-based petition.',
        type: 'Preparation',
        isRemote: true,
        caseId: '8',
        caseTitle: 'Martinez Immigration',
      ),
      // Today's appointments
      Appointment(
        id: '9',
        title: 'Case Strategy Meeting',
        startTime: today.add(const Duration(hours: 14)),
        endTime: today.add(const Duration(hours: 15)),
        clientName: 'Robert Smith',
        clientId: '1',
        location: 'Office',
        description: 'Develop strategy for upcoming deposition in personal injury case.',
        type: 'Strategy',
        isRemote: false,
        caseId: '1',
        caseTitle: 'Smith vs. Johnson',
      ),
      Appointment(
        id: '10',
        title: 'Client Check-in',
        startTime: today.add(const Duration(hours: 16)),
        endTime: today.add(const Duration(hours: 16, minutes: 30)),
        clientName: 'Michael Davis',
        clientId: '3',
        location: 'Phone Call',
        description: 'Regular check-in to update client on divorce proceedings.',
        type: 'Consultation',
        isRemote: true,
        caseId: '3',
        caseTitle: 'Davis Divorce',
      ),
    ];
  }

  // Tasks
  static List<Task> get tasks {
    final now = DateTime.now();
    final today = DateTime(now.year, now.month, now.day);
    
    return [
      Task(
        id: '1',
        title: 'Prepare Motion for Smith Case',
        description: 'Draft and file motion for summary judgment in the personal injury case.',
        dueDate: today.add(const Duration(days: 2)),
        priority: 'High',
        isCompleted: false,
        caseId: '1',
        caseTitle: 'Smith vs. Johnson',
        clientId: '1',
        clientName: 'Robert Smith',
      ),
      Task(
        id: '2',
        title: 'Review Williams Estate Documents',
        description: 'Review all estate documents and prepare summary for probate filing.',
        dueDate: today.add(const Duration(days: 3)),
        priority: 'Medium',
        isCompleted: false,
        caseId: '2',
        caseTitle: 'Williams Estate',
        clientId: '2',
        clientName: 'Sarah Williams',
      ),
      Task(
        id: '3',
        title: 'Prepare for Davis Hearing',
        description: 'Review case notes and prepare arguments for temporary custody hearing.',
        dueDate: today.add(const Duration(days: 1)),
        priority: 'High',
        isCompleted: false,
        caseId: '3',
        caseTitle: 'Davis Divorce',
        clientId: '3',
        clientName: 'Michael Davis',
      ),
      Task(
        id: '4',
        title: 'Draft LLC Operating Agreement',
        description: 'Prepare operating agreement for Thompson LLC with specific provisions for equity distribution.',
        dueDate: today.add(const Duration(days: 4)),
        priority: 'Medium',
        isCompleted: true,
        completedAt: today.subtract(const Duration(days: 1)),
        caseId: '4',
        caseTitle: 'Thompson LLC Formation',
        clientId: '4',
        clientName: 'Jennifer Thompson',
      ),
      Task(
        id: '5',
        title: 'Research Property Laws',
        description: 'Research relevant property laws and precedents for Brown boundary dispute case.',
        dueDate: today.add(const Duration(days: 2)),
        priority: 'Medium',
        isCompleted: false,
        caseId: '5',
        caseTitle: 'Brown Property Dispute',
        clientId: '5',
        clientName: 'James Brown',
      ),
      Task(
        id: '6',
        title: 'Update Billing Records',
        description: 'Update billing records for all active clients and prepare monthly invoices.',
        dueDate: today.add(const Duration(days: 1)),
        priority: 'Low',
        isCompleted: false,
      ),
      Task(
        id: '7',
        title: 'Schedule Client Meetings',
        description: 'Schedule follow-up meetings with clients for next month.',
        dueDate: today.add(const Duration(days: 2)),
        priority: 'Low',
        isCompleted: true,
        completedAt: today.subtract(const Duration(days: 2)),
      ),
      Task(
        id: '8',
        title: 'Draft Patent Application',
        description: 'Complete first draft of patent application for Garcia medical device.',
        dueDate: today.add(const Duration(days: 5)),
        priority: 'High',
        isCompleted: false,
        caseId: '6',
        caseTitle: 'Garcia Patent Application',
        clientId: '6',
        clientName: 'Carlos Garcia',
      ),
      Task(
        id: '9',
        title: 'Analyze Contract Terms',
        description: 'Analyze disputed contract terms and identify potential breaches for Wilson case.',
        dueDate: today.add(const Duration(days: 3)),
        priority: 'Medium',
        isCompleted: false,
        caseId: '7',
        caseTitle: 'Wilson Contract Dispute',
        clientId: '7',
        clientName: 'Thomas Wilson',
      ),
      Task(
        id: '10',
        title: 'Prepare Immigration Forms',
        description: 'Complete and review I-130 and I-485 forms for Martinez immigration case.',
        dueDate: today.add(const Duration(days: 4)),
        priority: 'High',
        isCompleted: false,
        caseId: '8',
        caseTitle: 'Martinez Immigration',
        clientId: '8',
        clientName: 'Elena Martinez',
      ),
      // Overdue tasks
      Task(
        id: '11',
        title: 'File Court Response',
        description: 'File response to opposing counsel\'s motion in Smith case.',
        dueDate: today.subtract(const Duration(days: 1)),
        priority: 'High',
        isCompleted: false,
        caseId: '1',
        caseTitle: 'Smith vs. Johnson',
        clientId: '1',
        clientName: 'Robert Smith',
      ),
      Task(
        id: '12',
        title: 'Call Insurance Adjuster',
        description: 'Follow up with insurance adjuster regarding settlement offer in Smith case.',
        dueDate: today.subtract(const Duration(days: 2)),
        priority: 'Medium',
        isCompleted: false,
        caseId: '1',
        caseTitle: 'Smith vs. Johnson',
        clientId: '1',
        clientName: 'Robert Smith',
      ),
    ];
  }

  // Documents
  static List<Document> get documents => [
    Document(
      id: '1',
      title: 'Smith Case - Accident Report',
      fileName: 'smith_accident_report.pdf',
      fileType: 'pdf',
      fileUrl: 'https://example.com/documents/smith_accident_report.pdf',
      fileSize: 2500000, // 2.5 MB
      uploadDate: DateTime(2023, 3, 20),
      caseId: '1',
      caseTitle: 'Smith vs. Johnson',
      clientId: '1',
      clientName: 'Robert Smith',
      description: 'Police report from the accident scene.',
      tags: ['Evidence', 'Report', 'Police'],
      isSharedWithClient: true,
    ),
    Document(
      id: '2',
      title: 'Smith Case - Medical Records',
      fileName: 'smith_medical_records.pdf',
      fileType: 'pdf',
      fileUrl: 'https://example.com/documents/smith_medical_records.pdf',
      fileSize: 5800000, // 5.8 MB
      uploadDate: DateTime(2023, 3, 25),
      caseId: '1',
      caseTitle: 'Smith vs. Johnson',
      clientId: '1',
      clientName: 'Robert Smith',
      description: 'Medical records from hospital visit after accident.',
      tags: ['Evidence', 'Medical', 'Hospital'],
      isSharedWithClient: true,
    ),
    Document(
      id: '3',
      title: 'Smith Case - Demand Letter',
      fileName: 'smith_demand_letter.docx',
      fileType: 'docx',
      fileUrl: 'https://example.com/documents/smith_demand_letter.docx',
      fileSize: 450000, // 450 KB
      uploadDate: DateTime(2023, 4, 10),
      caseId: '1',
      caseTitle: 'Smith vs. Johnson',
      clientId: '1',
      clientName: 'Robert Smith',
      description: 'Demand letter sent to insurance company.',
      tags: ['Correspondence', 'Demand', 'Insurance'],
      isSharedWithClient: false,
    ),
    Document(
      id: '4',
      title: 'Williams Estate - Will',
      fileName: 'williams_will.pdf',
      fileType: 'pdf',
      fileUrl: 'https://example.com/documents/williams_will.pdf',
      fileSize: 1200000, // 1.2 MB
      uploadDate: DateTime(2023, 2, 25),
      caseId: '2',
      caseTitle: 'Williams Estate',
      clientId: '2',
      clientName: 'Sarah Williams',
      description: 'Last will and testament of Mr. Williams.',
      tags: ['Will', 'Estate', 'Legal Document'],
      isSharedWithClient: true,
    ),
    Document(
      id: '5',
      title: 'Williams Estate - Asset Inventory',
      fileName: 'williams_asset_inventory.xlsx',
      fileType: 'xlsx',
      fileUrl: 'https://example.com/documents/williams_asset_inventory.xlsx',
      fileSize: 850000, // 850 KB
      uploadDate: DateTime(2023, 3, 5),
      caseId: '2',
      caseTitle: 'Williams Estate',
      clientId: '2',
      clientName: 'Sarah Williams',
      description: 'Inventory of all assets in the Williams estate.',
      tags: ['Assets', 'Inventory', 'Estate'],
      isSharedWithClient: true,
    ),
    Document(
      id: '6',
      title: 'Davis Divorce - Petition',
      fileName: 'davis_divorce_petition.pdf',
      fileType: 'pdf',
      fileUrl: 'https://example.com/documents/davis_divorce_petition.pdf',
      fileSize: 980000, // 980 KB
      uploadDate: DateTime(2023, 4, 8),
      caseId: '3',
      caseTitle: 'Davis Divorce',
      clientId: '3',
      clientName: 'Michael Davis',
      description: 'Divorce petition filed with the court.',
      tags: ['Petition', 'Divorce', 'Court Filing'],
      isSharedWithClient: true,
    ),
    Document(
      id: '7',
      title: 'Davis Divorce - Financial Disclosure',
      fileName: 'davis_financial_disclosure.xlsx',
      fileType: 'xlsx',
      fileUrl: 'https://example.com/documents/davis_financial_disclosure.xlsx',
      fileSize: 1100000, // 1.1 MB
      uploadDate: DateTime(2023, 4, 15),
      caseId: '3',
      caseTitle: 'Davis Divorce',
      clientId: '3',
      clientName: 'Michael Davis',
      description: 'Financial disclosure statement for divorce proceedings.',
      tags: ['Financial', 'Disclosure', 'Divorce'],
      isSharedWithClient: true,
    ),
    Document(
      id: '8',
      title: 'Davis Divorce - Custody Proposal',
      fileName: 'davis_custody_proposal.docx',
      fileType: 'docx',
      fileUrl: 'https://example.com/documents/davis_custody_proposal.docx',
      fileSize: 720000, // 720 KB
      uploadDate: DateTime(2023, 4, 20),
      caseId: '3',
      caseTitle: 'Davis Divorce',
      clientId: '3',
      clientName: 'Michael Davis',
      description: 'Proposed custody arrangement for children.',
      tags: ['Custody', 'Proposal', 'Children'],
      isSharedWithClient: false,
    ),
    Document(
      id: '9',
      title: 'Thompson LLC - Articles of Organization',
      fileName: 'thompson_articles.pdf',
      fileType: 'pdf',
      fileUrl: 'https://example.com/documents/thompson_articles.pdf',
      fileSize: 650000, // 650 KB
      uploadDate: DateTime(2023, 1, 15),
      caseId: '4',
      caseTitle: 'Thompson LLC Formation',
      clientId: '4',
      clientName: 'Jennifer Thompson',
      description: 'Articles of Organization filed with the Secretary of State.',
      tags: ['LLC', 'Formation', 'Legal Document'],
      isSharedWithClient: true,
    ),
    Document(
      id: '10',
      title: 'Thompson LLC - Operating Agreement',
      fileName: 'thompson_operating_agreement.docx',
      fileType: 'docx',
      fileUrl: 'https://example.com/documents/thompson_operating_agreement.docx',
      fileSize: 890000, // 890 KB
      uploadDate: DateTime(2023, 1, 20),
      caseId: '4',
      caseTitle: 'Thompson LLC Formation',
      clientId: '4',
      clientName: 'Jennifer Thompson',
      description: 'Operating agreement for the LLC detailing ownership and management.',
      tags: ['LLC', 'Agreement', 'Management'],
      isSharedWithClient: true,
    ),
    Document(
      id: '11',
      title: 'Brown Property - Survey Report',
      fileName: 'brown_survey.pdf',
      fileType: 'pdf',
      fileUrl: 'https://example.com/documents/brown_survey.pdf',
      fileSize: 3200000, // 3.2 MB
      uploadDate: DateTime(2023, 4, 5),
      caseId: '5',
      caseTitle: 'Brown Property Dispute',
      clientId: '5',
      clientName: 'James Brown',
      description: 'Professional survey of the property boundaries.',
      tags: ['Survey', 'Property', 'Evidence'],
      isSharedWithClient: true,
    ),
    Document(
      id: '12',
      title: 'Brown Property - Deed',
      fileName: 'brown_deed.pdf',
      fileType: 'pdf',
      fileUrl: 'https://example.com/documents/brown_deed.pdf',
      fileSize: 1500000, // 1.5 MB
      uploadDate: DateTime(2023, 4, 10),
      caseId: '5',
      caseTitle: 'Brown Property Dispute',
      clientId: '5',
      clientName: 'James Brown',
      description: 'Property deed showing legal boundaries and ownership.',
      tags: ['Deed', 'Property', 'Legal Document'],
      isSharedWithClient: true,
    ),
  ];

  // Notifications
  static List<AppNotification> get notifications {
    final now = DateTime.now();
    
    return [
      AppNotification(
        id: '1',
        title: 'Upcoming Court Date',
        message: 'Reminder: Court hearing for Davis Divorce case tomorrow at 9:00 AM.',
        timestamp: now.subtract(const Duration(hours: 2)),
        isRead: false,
        type: 'Case',
        relatedId: '3',
        relatedType: 'case',
      ),
      AppNotification(
        id: '2',
        title: 'Document Uploaded',
        message: 'New document "Smith Case - Medical Records" has been uploaded.',
        timestamp: now.subtract(const Duration(hours: 5)),
        isRead: true,
        type: 'Document',
        relatedId: '2',
        relatedType: 'document',
      ),
      AppNotification(
        id: '3',
        title: 'Task Overdue',
        message: 'Task "File Court Response" is now overdue.',
        timestamp: now.subtract(const Duration(days: 1)),
        isRead: false,
        type: 'Task',
        relatedId: '11',
        relatedType: 'task',
      ),
      AppNotification(
        id: '4',
        title: 'New Appointment',
        message: 'New appointment scheduled with Robert Smith for tomorrow at 2:00 PM.',
        timestamp: now.subtract(const Duration(days: 1, hours: 4)),
        isRead: true,
        type: 'Appointment',
        relatedId: '9',
        relatedType: 'appointment',
      ),
      AppNotification(
        id: '5',
        title: 'Payment Received',
        message: 'Payment of \$1,500.00 received from Sarah Williams.',
        timestamp: now.subtract(const Duration(days: 2)),
        isRead: true,
        type: 'Payment',
        relatedId: '2',
        relatedType: 'payment',
      ),
      AppNotification(
        id: '6',
        title: 'Case Status Update',
        message: 'Smith vs. Johnson case has been scheduled for trial on June 15, 2023.',
        timestamp: now.subtract(const Duration(days: 3)),
        isRead: true,
        type: 'Case',
        relatedId: '1',
        relatedType: 'case',
      ),
      AppNotification(
        id: '7',
        title: 'New Client',
        message: 'Elena Martinez has been added as a new client.',
        timestamp: now.subtract(const Duration(days: 5)),
        isRead: true,
        type: 'Client',
        relatedId: '8',
        relatedType: 'client',
      ),
    ];
  }

  // Payments
  static List<Payment> get payments => [
    Payment(
      id: '1',
      amount: 2500.00,
      date: DateTime(2023, 3, 25),
      status: 'Paid',
      clientId: '1',
      clientName: 'Robert Smith',
      caseId: '1',
      caseTitle: 'Smith vs. Johnson',
      description: 'Initial retainer payment',
      paymentMethod: 'Credit Card',
      invoiceId: 'INV-2023-001',
      transactionId: 'TXN-123456',
    ),
    Payment(
      id: '2',
      amount: 1500.00,
      date: DateTime(2023, 4, 15),
      status: 'Paid',
      clientId: '2',
      clientName: 'Sarah Williams',
      caseId: '2',
      caseTitle: 'Williams Estate',
      description: 'Probate filing fees and services',
      paymentMethod: 'Bank Transfer',
      invoiceId: 'INV-2023-002',
      transactionId: 'TXN-234567',
    ),
    Payment(
      id: '3',
      amount: 3000.00,
      date: DateTime(2023, 4, 10),
      status: 'Paid',
      clientId: '3',
      clientName: 'Michael Davis',
      caseId: '3',
      caseTitle: 'Davis Divorce',
      description: 'Retainer for divorce proceedings',
      paymentMethod: 'Credit Card',
      invoiceId: 'INV-2023-003',
      transactionId: 'TXN-345678',
    ),
    Payment(
      id: '4',
      amount: 1200.00,
      date: DateTime(2023, 1, 20),
      status: 'Paid',
      clientId: '4',
      clientName: 'Jennifer Thompson',
      caseId: '4',
      caseTitle: 'Thompson LLC Formation',
      description: 'LLC formation services and filing fees',
      paymentMethod: 'Credit Card',
      invoiceId: 'INV-2023-004',
      transactionId: 'TXN-456789',
    ),
    Payment(
      id: '5',
      amount: 2000.00,
      date: DateTime(2023, 4, 5),
      status: 'Paid',
      clientId: '5',
      clientName: 'James Brown',
      caseId: '5',
      caseTitle: 'Brown Property Dispute',
      description: 'Retainer for property dispute case',
      paymentMethod: 'Check',
      invoiceId: 'INV-2023-005',
      transactionId: 'TXN-567890',
    ),
    Payment(
      id: '6',
      amount: 2500.00,
      date: DateTime(2023, 5, 15),
      status: 'Pending',
      clientId: '6',
      clientName: 'Carlos Garcia',
      caseId: '6',
      caseTitle: 'Garcia Patent Application',
      description: 'Patent application services and filing fees',
      paymentMethod: 'Credit Card',
      invoiceId: 'INV-2023-006',
      transactionId: null,
    ),
    Payment(
      id: '7',
      amount: 1800.00,
      date: DateTime(2023, 4, 20),
      status: 'Paid',
      clientId: '7',
      clientName: 'Thomas Wilson',
      caseId: '7',
      caseTitle: 'Wilson Contract Dispute',
      description: 'Retainer for contract dispute case',
      paymentMethod: 'Bank Transfer',
      invoiceId: 'INV-2023-007',
      transactionId: 'TXN-678901',
    ),
    Payment(
      id: '8',
      amount: 1500.00,
      date: DateTime(2023, 6, 1),
      status: 'Pending',
      clientId: '8',
      clientName: 'Elena Martinez',
      caseId: '8',
      caseTitle: 'Martinez Immigration',
      description: 'Immigration petition services and filing fees',
      paymentMethod: 'Credit Card',
      invoiceId: 'INV-2023-008',
      transactionId: null,
    ),
  ];
}
